version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
            command: docker build . -t vanandrew/dglabimg:v1.00
            no_output_timeout: "3h"
      - run: docker push vanandrew/dglabimg:v1.00
